version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gerenciador_eventos_db
    environment:
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: gerenciadoreventos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: