# Conexão com o PostgreSQL do Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciadoreventos
spring.datasource.username=gabriel
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Chave secreta para assinar o JWT (Em produção, use algo complexo e guarde em variável de ambiente)
api.security.token.secret=minha-chave-secreta-super-protegida